[book]
authors = ["MapHero Contributors"]
language = "en"
multilingual = false
src = "src"
title = "MapHero Native Developer Documentation"

[output.html]
additional-css = ["diff.css"]
additional-js = []

[preprocessor.alerts]

[preprocessor.mermaid]
command = "mdbook-mermaid"
