MH_IOS_SDK_HEADERS = [
    "src/MHAnnotationImage.h",
    "src/MHAnnotationView.h",
    "src/MHCalloutView.h",
    "src/MHCameraChangeReason.h",
    "src/MHCompassButton.h",
    "src/MHMapProjection.h",
    "src/MHMapView+IBAdditions.h",
    "src/MHMapViewDelegate.h",
    "src/MHMapView.h",
    "src/MHUserLocation.h",
    "src/MHUserLocationAnnotationView.h",
    "src/MHUserLocationAnnotationViewStyle.h",
    "src/MHScaleBar.h",
]

MH_IOS_PUBLIC_HEADERS = [
    "src/Mapbox.h",
]

MH_IOS_PRIVATE_HEADERS = [
    "src/NSOrthography+MHAdditions.h",
    "src/UIDevice+MHAdditions.h",
    "src/UIImage+MHAdditions.h",
    "src/MHUserLocationHeadingArrowLayer.h",
    "src/MHUserLocationHeadingIndicator.h",
    "src/UIColor+MHAdditions.h",
    "src/MHMapAccessibilityElement.h",
    "src/UIViewController+MHAdditions.h",
    "src/UIView+MHAdditions.h",
    "src/MHFaux3DUserLocationAnnotationView.h",
    "src/MHUserLocationHeadingBeamLayer.h",
    "src/MHAnnotationContainerView.h",
    "src/MHAnnotationContainerView_Private.h",
    "src/MHAnnotationImage_Private.h",
    "src/MHAnnotationView_Private.h",
    "src/MHCompassButton_Private.h",
    "src/MHMapView_Private.h",
    "src/MHUserLocationAnnotationView_Private.h",
    "src/MHUserLocation_Private.h",
    "src/MHCompactCalloutView.h",
    "src/MHMapView+Impl.h",
    "src/MHMapView+Metal.h",
    "src/MHMapView+OpenGL.h",
]

MH_IOS_PUBLIC_OBJC_SOURCE = [
    "src/MHAnnotationContainerView.m",
    "src/MHAnnotationImage.m",
    "src/MHCompactCalloutView.m",
    "src/MHUserLocation.m",
    "src/MHUserLocationAnnotationView.m",
    "src/MHUserLocationAnnotationViewStyle.m",
    "src/MHUserLocationHeadingArrowLayer.m",
    "src/MHUserLocationHeadingBeamLayer.m",
    "src/NSOrthography+MHAdditions.m",
    "src/UIDevice+MHAdditions.m",
    "src/UIView+MHAdditions.m",
    "src/UIViewController+MHAdditions.m",
]

MH_IOS_PUBLIC_OBJCPP_SOURCE = [
    "src/MHAnnotationView.mm",
    "src/MHCompassButton.mm",
    "src/MHFaux3DUserLocationAnnotationView.mm",
    "src/MHMapAccessibilityElement.mm",
    "src/MHMapProjection.mm",
    "src/MHMapView.mm",
    "src/MHMapView+Impl.mm",
    "src/MHScaleBar.mm",
    "src/UIColor+MHAdditions.mm",
    "src/UIImage+MHAdditions.mm",
]
MH_IOS_PUBLIC_OBJCPP_OPENGL_SOURCE = [
    "src/MHMapView+OpenGL.mm",
]
MH_IOS_PUBLIC_OBJCPP_METAL_SOURCE = [
    "src/MHMapView+Metal.mm",
]

MH_PUBLIC_IOS_APP_SOPURCE = [
    "app/MBXAnnotationView.m",
    "app/MBXAppDelegate.m",
    "app/MBXCustomCalloutView.h",
    "app/MBXCustomCalloutView.m",
    "app/MBXCustomLocationViewController.m",
    "app/MBXEmbeddedMapViewController.m",
    "app/MBXFrameTimeGraphView.m",
    "app/MBXOfflinePacksTableViewController.m",
    "app/MBXOrnamentsViewController.m",
    "app/MBXSnapshotsViewController.m",
    "app/MBXState.m",
    "app/MBXStateManager.m",
    "app/MBXUserLocationAnnotationView.m",
    "app/MBXViewController.mm",
    "app/main.m",
    "app/MBXAnnotationView.h",
    "app/MBXAppDelegate.h",
    "app/MBXCustomLocationViewController.h",
    "app/MBXEmbeddedMapViewController.h",
    "app/MBXFrameTimeGraphView.h",
    "app/MBXOfflinePacksTableViewController.h",
    "app/MBXOrnamentsViewController.h",
    "app/MBXSnapshotsViewController.h",
    "app/MBXState.h",
    "app/MBXStateManager.h",
    "app/MBXUserLocationAnnotationView.h",
    "app/MBXViewController.h",
    "app/MHMapView_Experimental.h",
]
