name: ios-ci

on:
  workflow_dispatch:
    inputs:
      release:
        type: choice
        default: no
        options:
          - full
          - pre
          - no
        description: Whether to make a release, choose full release (uses platform/ios/VERSION) or pre-release
      pre_release_version:
        type: string
        default: ''
        description: Version (only for pre-releases)
  push:
    branches:
      - main
      - ios-*.*.x
    tags:
      - 'ios-*'
  
  pull_request:
    branches:
      - '*'

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ github.event_name != 'workflow_dispatch' && steps.changed-files-yaml.outputs.ios_any_modified != 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Get all iOS files that have changed
        if: github.event_name != 'workflow_dispatch'
        id: changed-files-yaml
        uses: tj-actions/changed-files@v44
        with:
          files_yaml_from_source_file: .github/changed-files.yml

      - name: Run step if test file(s) change
        if: steps.changed-files-yaml.outputs.ios_any_modified == 'true'  
        run: |
          echo "One or more iOS file(s) has changed."
          echo "List of changes: ${{ steps.changed-files-yaml.outputs.ios_all_changed_files }}"
      
  ios-build:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: [self-hosted, macOS, ARM64]
    concurrency:
      # cancel jobs on PRs only
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    env:
      BUILDTYPE: Debug
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
    defaults:
      run:
        working-directory: platform/ios
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Cache Bazel
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-
          path: ~/.cache/bazel

      - name: Build Example (Swift) App
        run: bazel build //platform/ios/app-swift:MapLibreApp --//:renderer=metal

      - name: Check debug symbols
        run: bazel run //platform:check-public-symbols --//:renderer=metal

      - name: Lint plist files
        run: bazel run //platform/ios:lint-plists --//:renderer=metal

      - name: Running iOS tests
        run: bazel test //platform/ios/test:ios_test --test_output=errors --//:renderer=metal

      - name: Running iOS UI tests (Address+UB Sanitizer)
        run: bazel test //platform/ios/iosapp-UITests:uitest --test_output=errors --//:renderer=metal --features=include_clang_rt --copt=-fsanitize=undefined --linkopt=-fsanitize=undefined --copt=-fsanitize-recover=null --linkopt=-fsanitize-recover=null

      # Create .zip file and upload as artifact
      - name: Create and upload RenderTestApp.zip
        run: |
          set -e
          bazel run //platform/ios:xcodeproj --@rules_xcodeproj//xcodeproj:extra_common_flags="--//:renderer=metal"
          build_dir="$(mktemp -d)"
          xcodebuild build-for-testing -scheme RenderTest -project MapLibre.xcodeproj -derivedDataPath "$build_dir"
          render_test_app_dir="$(dirname "$(find "$build_dir" -name RenderTestApp.app)")"
          cd "$render_test_app_dir"
          zip -r RenderTestApp.zip RenderTestApp.app
          echo "::set-output name=artifact_path::$(pwd)/RenderTestApp.zip"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios-app-artifact
          path: ${{ steps.create-and-upload-artifact.outputs.artifact_path }}
